In [8]:
import torch
import torch.nn
import copy
import eulerCart
import gas

A = torch.zeros((3, 3), device='cpu')

A[:, 0] = 1

B = A @ A.transpose(0, 1)

C = torch.nn.Linear(3, 3, False)

ifAP = A > 0

B = A.clone()


B[1, :] = 0.5

torch.zeros_like(A)

K = torch.rand_like(A)

print(K)

a = K[:, 1].clone()
b = K[:, 2].clone()

K[:, 1] = b
K[:, 2] = a

print(K)

uL = torch.tensor([1,
                   2,
                   0,
                   4.50000000000000])

uR = torch.tensor([0.100000000000000,
                   0.0400000000000000,
                   0.0300000000000000,
                   5.01250000000000, ])
print(gas.RoeSolver2(uL, uL, torch.tensor(1.5)))


A[[1,2],[0,1]] = 4

A.view(-1,9)[:,[1,2]] = 7

A.view(-1)[1:]


tensor([[0.7832, 0.0508, 0.6722],
        [0.7301, 0.4415, 0.5817],
        [0.6169, 0.8104, 0.0502]])
tensor([[0.7832, 0.6722, 0.0508],
        [0.7301, 0.5817, 0.4415],
        [0.6169, 0.0502, 0.8104]])
tensor([ 2.0000,  5.2500,  0.0000, 11.5000])


tensor([7., 7., 4., 0., 0., 1., 4., 0.])