In [1]:
import torch
import torch.nn
import copy
import eulerCart
import eulerCart.gas as gas
import eulerCart.cart as cart

A = torch.zeros((3, 3), device='cpu')

A[:, 0] = 1

B = A @ A.transpose(0, 1)

C = torch.nn.Linear(3, 3, False)

ifAP = A > 0

B = A.clone()


B[1, :] = 0.5

torch.zeros_like(A)

K = torch.rand_like(A)

print(K)

a = K[:, 1].clone()
b = K[:, 2].clone()

K[:, 1] = b
K[:, 2] = a

print(K)

uL = torch.tensor([1,
                   2,
                   0,
                   4.50000000000000])

uR = torch.tensor([0.100000000000000,
                   0.0400000000000000,
                   0.0300000000000000,
                   5.01250000000000, ])
print(gas.RoeSolver2(uL, uL, torch.tensor(1.5)))


A[[1,2],[0,1]] = 4

A.view(-1,9)[:,[1,2]] = 7

A.view(-1)[1:]

tensor([[0.0576, 0.1772, 0.7735],
        [0.5312, 0.5180, 0.9925],
        [0.3608, 0.8883, 0.8872]])
tensor([[0.0576, 0.7735, 0.1772],
        [0.5312, 0.9925, 0.5180],
        [0.3608, 0.8872, 0.8883]])
tensor([ 2.0000,  5.2500,  0.0000, 11.5000])


tensor([7., 7., 4., 0., 0., 1., 4., 0.])

In [2]:
torch.manual_seed(0)
A = torch.rand((3, 4, 3))
nz_subs = torch.nonzero(A < 0.5, as_tuple=True)
print(A[nz_subs])

B = A.repeat(5, 1, 1, 1)
print(B[:, nz_subs[0], nz_subs[1], nz_subs[2]].view((5,-1)))

tensor([0.4963, 0.0885, 0.1320, 0.3074, 0.4901, 0.4556, 0.3489, 0.4017, 0.0223,
        0.1689, 0.2939, 0.1610, 0.2823, 0.3971, 0.4194, 0.0362, 0.1852, 0.3734,
        0.3051, 0.1759, 0.2698, 0.1507, 0.0317])
tensor([[0.4963, 0.0885, 0.1320, 0.3074, 0.4901, 0.4556, 0.3489, 0.4017, 0.0223,
         0.1689, 0.2939, 0.1610, 0.2823, 0.3971, 0.4194, 0.0362, 0.1852, 0.3734,
         0.3051, 0.1759, 0.2698, 0.1507, 0.0317],
        [0.4963, 0.0885, 0.1320, 0.3074, 0.4901, 0.4556, 0.3489, 0.4017, 0.0223,
         0.1689, 0.2939, 0.1610, 0.2823, 0.3971, 0.4194, 0.0362, 0.1852, 0.3734,
         0.3051, 0.1759, 0.2698, 0.1507, 0.0317],
        [0.4963, 0.0885, 0.1320, 0.3074, 0.4901, 0.4556, 0.3489, 0.4017, 0.0223,
         0.1689, 0.2939, 0.1610, 0.2823, 0.3971, 0.4194, 0.0362, 0.1852, 0.3734,
         0.3051, 0.1759, 0.2698, 0.1507, 0.0317],
        [0.4963, 0.0885, 0.1320, 0.3074, 0.4901, 0.4556, 0.3489, 0.4017, 0.0223,
         0.1689, 0.2939, 0.1610, 0.2823, 0.3971, 0.4194, 0.0362, 0.1852, 0

In [5]:
A = torch.tensor([0, 1, 1, 0])
B = torch.tensor([0, 1, 1, 0, 0, 0, 0, 0, 0])
A = A.reshape(4, 1) @ B.reshape(1, -1)
print(cart.sub2indFromBool_pytorch(A))

print(f"{1:03d}")

tensor([4.4444, 8.4444, 4.8889, 8.8889])
001
